/*
  GUI server (run from the GUI/ folder) that:
  - serves the GUI static files from GUI/
  - executes predict_and_explain.py from the project root (one level up)
  - exposes /output to serve generated files from <project-root>/output

  Usage (from GUI/):
    npm init -y
    npm i express
    node server.js

  Open: http://localhost:3000

  Options:
    - PYTHON_BIN: python executable (Windows usually "python"; mac/linux "python3")
    - PORT: server port
*/

const path = require("path");
const express = require("express");
const { spawn } = require("child_process");
const fs = require("fs");

const app = express();
app.use(express.json());

const inProduction = String(process.env.NODE_ENV || "").toLowerCase() === "production";

// Dev-only CORS: allows serving the GUI from a different origin/port (e.g., VSCode Live Server)
// while keeping production as same-origin by default.
if (!inProduction) {
  app.use((req, res, next) => {
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "GET,POST,OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type");
    if (req.method === "OPTIONS") return res.sendStatus(204);
    next();
  });
}


// Folder structure:
// <project-root>/predict_and_explain.py
// <project-root>/GUI/{index.html, app.js, styles.css, server.js}
const GUI_DIR = __dirname;
const PROJECT_ROOT = path.resolve(__dirname, "..");

// Serve GUI assets (index.html, app.js, styles.css, etc.)
app.use(express.static(GUI_DIR));

// Serve outputs generated by the python script (relative to PROJECT_ROOT)
app.use("/output", express.static(path.join(PROJECT_ROOT, "output")));

// Small helper
function getArgValue(args, flag, fallback) {
  const i = args.indexOf(flag);
  if (i >= 0 && i + 1 < args.length) return args[i + 1];
  return fallback;
}


// List files in a directory (relative to PROJECT_ROOT). Used by the GUI to locate output filenames (e.g., betas with suffixes).
// Example: GET /api/list?dir=output/abnormal-heartbeat-c1/LogisticRegression/shap/predicted/22
app.get("/api/list", (req, res) => {
  const dir = String(req.query.dir || "").replace(/\\/g, "/").replace(/^\//, "");
  const only = String(req.query.only || "").toLowerCase(); // "dirs" | "files" | ""
  if (!dir) return res.status(400).json({ ok: false, error: "Missing dir query parameter" });

  // Restrict to output/ to avoid arbitrary FS browsing
  if (!dir.startsWith("output/")) {
    return res.status(400).json({ ok: false, error: "dir must start with output/" });
  }

  const abs = path.join(PROJECT_ROOT, dir);
  try {
    const st = fs.statSync(abs);
    if (!st.isDirectory()) return res.status(400).json({ ok: false, error: "Not a directory" });

    const entries = fs.readdirSync(abs, { withFileTypes: true })
      .filter(e => !e.name.startsWith("."))
      .map(e => ({ name: e.name, type: e.isDirectory() ? "dir" : "file" }));

    const filtered = (only === "dirs") ? entries.filter(e => e.type === "dir")
                    : (only === "files") ? entries.filter(e => e.type === "file")
                    : entries;

    return res.json({ ok: true, entries: filtered });
  } catch (e) {
    return res.status(404).json({ ok: false, error: String(e.message || e) });
  }
});

app.post("/api/run", (req, res) => {
  const args = req.body && req.body.args;

  if (!Array.isArray(args) || args.length === 0) {
    return res.status(400).json({ ok: false, error: "args must be a non-empty array" });
  }

  // Basic safety: only allow predict_and_explain.py
  const script = args[0];
  if (script !== "predict_and_explain.py") {
    return res.status(400).json({ ok: false, error: "Only predict_and_explain.py is allowed" });
  }

  // Ensure the script exists where we expect it.
  const scriptPath = path.join(PROJECT_ROOT, "predict_and_explain.py");
  if (!fs.existsSync(scriptPath)) {
    return res.status(500).json({
      ok: false,
      error: `predict_and_explain.py not found at: ${scriptPath}. Expected it one level above GUI/.`
    });
  }

  const python = process.env.PYTHON_BIN || "python";
  const cliArgs = [scriptPath, ...args.slice(1)];

  const proc = spawn(python, cliArgs, { cwd: PROJECT_ROOT });

  let stdout = "";
  let stderr = "";

  proc.stdout.on("data", (b) => (stdout += b.toString()));
  proc.stderr.on("data", (b) => (stderr += b.toString()));

  proc.on("close", (code) => {
    if (code !== 0) {
      return res.status(500).json({
        ok: false,
        code,
        stdout,
        stderr: stderr || `Process exited with code ${code}`,
      });
    }

    // Provide a "best guess" outputs base to help the UI locate results.
    const dataset = getArgValue(args, "-D", "unknown");
    const model = getArgValue(args, "-M", "unknown");
    const expl = getArgValue(args, "-E", "unknown");
    const label = getArgValue(args, "-L", "unknown");
    const start = getArgValue(args, "-s", "0");
    const outRoot = getArgValue(args, "-o", "output");

    const outputsBase = path.join(outRoot, dataset, model, expl, label, String(start));
    const outputsBaseExists = fs.existsSync(path.join(PROJECT_ROOT, outputsBase));

    return res.json({
      ok: true,
      code,
      stdout,
      stderr,
      outputs_base: outputsBaseExists
        ? `/output/${dataset}/${model}/${expl}/${label}/${start}`
        : `/output/${dataset}/${model}/${expl}/${label}`
    });
  });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`GUI server running at http://localhost:${PORT}`);
  console.log(`PROJECT_ROOT: ${PROJECT_ROOT}`);
  console.log(`Serving GUI from: ${GUI_DIR}`);
});
